version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=djangosecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=moinaksDB
      - DB_USER=moinakdey
      - DB_PASS=qwerty@8
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=moinaksDB
      - POSTGRES_USER=moinakdey
      - POSTGRES_PASSWORD=qwerty@8