# Generated by Django 4.2 on 2023-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField(verbose_name='Long Url')),
                ('short_url', models.CharField(max_length=200, verbose_name='Short Url')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
    ]
