# Generated by Django 4.2 on 2023-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='pid',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='ID'),
        ),
    ]
