LOGOS = [
    {
        "name":"youtube",
        "logo": "https://www.freepnglogos.com/uploads/youtube-logo-red-hd-13.png",
    },
    {
        "name":"spotify",
        "logo":"https://www.pngmart.com/files/22/Spotify-Logo-PNG-HD.png"
    },
    {
        "name":"google",
        "logo":"https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png"
    },
    {
        "name":"yahoo",
        "logo":"https://www.freepnglogos.com/uploads/yahoo-logo-png/yahoo-logo-png-y-logo-yahoo-social-media-icons-2.png"
    },
    {
        "name":"linkedin",
        "logo":"https://static.vecteezy.com/system/resources/previews/018/930/587/original/linkedin-logo-linkedin-icon-transparent-free-png.png"
    },
    {
        "name":"github",
        "logo":"https://www.freepnglogos.com/uploads/512x512-logo-png/512x512-logo-github-icon-35.png"
    },
    {
        "name":"instagram",
        "logo":"https://www.freepnglogos.com/uploads/logo-ig-png/logo-ig-instagram-windows-phone-all-you-need-know-9.png"
    }
]